OPENAI_API_KEY = "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"
OPENAI_MODEL = "davinci-002"



NEO4J_URI = "bolt://54.161.198.7:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "propulsion-universe-consideration"